# Generated by Django 5.2.6 on 2025-09-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaxCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название свечи')),
                ('short_description', models.CharField(help_text="Короткое описание под названием (например: 'Натуральная восковая свеча')", max_length=300, verbose_name='Краткое описание')),
                ('detailed_description', models.TextField(help_text='Полное описание свечи с деталями', verbose_name='Подробное описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в рублях', max_digits=10, verbose_name='Цена')),
                ('weight', models.CharField(default='100г', help_text='Например: 50г, 100г, 200г', max_length=50, verbose_name='Вес')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 369x365px для карточки товара', upload_to='wax_candles/', verbose_name='Изображение свечи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная свеча')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая свеча')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Восковая свеча',
                'verbose_name_plural': 'Восковые свечи',
                'ordering': ['-created_at'],
            },
        ),
    ]
